#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_MC,
    MUGSHOT_OLD_ARCHIE,
    MUGSHOT_GREEHASEET,
    MUGSHOT_NESSIE,
    MUGSHOT_SAPPY,
    MUGSHOT_ADDISAMAP,
    MUGSHOT_MAXIE,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_ALT,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
